### ISSUE TITLE
Spaces in FilePath Compatibility

### ISSUE THREAD

**Issue by NickCondon** [ElisabethKugler/ZFVascularQuantification#2]
Had a user attempt to run the ZFVascQuant_GUI_02122020.ijm macro file pointing at a directory path that contained spaces. 

This can be overcome by modifying Line155 of that code to include [square brackets] around the path +filename
eg. run("Bio-Formats Importer", "open=[" + path + filelist[i] + "] autoscale color_mode=Default split_channels view=Hyperstack stack_order=XYCZT");

**Comment by ElisabethKugler** [comment]
Apologies for the delay - fixing it now. Thank you, Nick!
