### ISSUE TITLE
GitHub link  as filepath not Windows compatible

### ISSUE THREAD

**Issue by NickCondon** [ElisabethKugler/ZFVascularQuantification#3]
Line 197 creates a directory which contains a link to the github repository. This link is not compatible for windows as the file path slashes point the wrong way. 

The command File.separator; can be used to match the system file seperator if required (eg. fs = File.separator;    )  but would likely result in excess subdirectories anyway.

Perhaps making a .txt file in the directory with the relevant github directory could be of use, or printing this info into the log window.

**Comment by ElisabethKugler** [comment]
Many thanks for pointing this out!
The link to GitHub was a mistake - corrected the line to 
`SIFTDir = path + "/SIFT/";`
